import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/NavBarPage";
import WorkoutProvider from "./Context/WorkOutContext";
// import PlanList from "./components/myPlanPage/PlanList";
import AddToTodayPlanButton from "./components/Button/addToTodayPlanButton";
import PlanList from "./components/myPlanPage/PlanList";
 import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "./components/footer/FooterPage";
// import Footer from "./components/footer/FooterPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <WorkoutProvider>
        <Navbar />
        <ToastContainer />
        
         
        <main>
{children}
        </main>
        <Footer />
        </WorkoutProvider>

        </body>
        
    </html>
  );
}
